kind: pipeline
name: default

steps:
# - name: env
#   image: busybox
#   commands:
#     - env

- name: secret
  image: xynova/aws-kubectl
  environment:
    AWS_ACCOUNT_ID:
      from_secret: aws_account_id
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    KUBECONFIG:
      from_secret: kubeconfig
  commands:
    - echo "$KUBECONFIG" > /tmp/k3s.yaml
    - KUBECONFIG=/tmp/k3s.yaml
    - DOCKER_PASSWORD=$(aws ecr get-login --no-include-email --region eu-west-1 | cut -d ' ' -f6)
    - echo ${DOCKER_PASSWORD}
    - cat /tmp/k3s.yaml

    # - |
    #   kubectl create secret docker-registry aws-ecr-credentials \
    #   --docker-server=${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com --docker-username=AWS \
    #   --docker-password=${DOCKER_PASSWORD} --dry-run -o yaml | kubectl apply -f -

# - name: publish
#   image: plugins/ecr
#   environment:
#     AWS_ACCOUNT_ID:
#       from_secret: aws_account_id
#     AWS_ACCESS_KEY_ID:
#       from_secret: aws_access_key_id
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: aws_secret_access_key
#   settings:
#     access_key: ${AWS_ACCESS_KEY_ID}
#     secret_key: ${AWS_SECRET_ACCESS_KEY}
#     repo: drone-release
#     registry: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com
#     region: eu-west-1
#     build_args:
#       - version=1.0
#
